apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "stephenwike.com"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ .Values.name }}-service
          servicePort: 80
